### ISSUE TITLE
192.168.1

### ISSUE THREAD

**Issue by Realize0uid1000** [nokey-54/FFmpeg-livestream-docker#1]
I'm on right Im a man ♂️ no reverse roles im single UID 1000

**Comment by Realize0uid1000** [comment]
https://music.youtube.com/watch?v=9VVet7oTWAE&feature=sharehttps://music.youtube.com/watch?v=9VVet7oTWAE&feature=sharehttps://www.facebook.com/profile.php?id=100092260255895&mibextid=ZbWKwL

**Comment by nokey-54** [comment]
please reopen if serious
